# SPDX-FileCopyrightText: 2023 The Input-Leap Developers
#
# SPDX-License-Identifier: GPL-2.0-only

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
