# SPDX-FileCopyrightText: 2023 The Input-Leap Developers
#
# SPDX-License-Identifier: GPL-2.0-only

[package]
name = "input-leap-rs-client-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
input-leap-rs-core = { path = "../../../lib/core/" }
