# SPDX-FileCopyrightText: 2023 The Input-Leap Developers
#
# SPDX-License-Identifier: GPL-2.0-only

name: Conventional Commits

on:
  pull_request:

jobs:
  test-pr-commit-msg:
    name: Test the commit message for PR.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.1.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
